version: '3'
services:
  postgres:
    image: postgres
    container_name: bookStore
    environment:
      POSTGRES_DB: bookStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
